enum actionTypes {
  BREWERY_SUCCESS = "BREWERY_SUCCESS",
  BREWERY_ERROR = "BREWERY_ERROR",
  BREWERY_DETAILS_SUCCESS = "BREWERY_DETAILS_SUCCESS",
  BREWERY_DETAILS_ERROR = "BREWERY_DETAILS_ERROR",
}

export default actionTypes;
